### ISSUE TITLE
Question: Performance problems

### ISSUE THREAD

**Issue by stastnypremysl** [darwinex/dwxconnect#9] opened 2022-03-06 17:33 UTC
Hello.

I studied your code and I am unsure, whether the solution of communication with Metatrader through creating and deleting files is fast enough. 

There must be made serialization by OS when changing folder, the OS must maintain the filesystem integrity,... and there are many other overheads of this solution. I am worried, whether this overhead might take too much ms to be done.

Did you make any benchmarks, when you migrated from ZeroMQ? Is my intuition about the slowness of the solution correct?

Thanks.

**Comment by teddywaweru** [comment] 2022-03-27 19:38
Having built using the ZeroMQ connector before, I've tested this solution out, & it is drammatically slower, to load MetaTrader data into the program's pipeline.  I'm inclined to use time delays (200 - 500ms) in my code to allow time for the json docs to be created in the file system & loaded. I had to implement the same on the ZeroMQ, but the difference in loading time is significant (~50ms).
 Async functionality would be plausible, but majority of my program is step flow is linear.
The issue then is that any query to MetaTrader would have this workflow. Maybe there could be a strategy of including functionality that enables capturing the EA's response & passing it to the program BEFORE creating a text file...

**Comment by elvinex** [comment] 2022-03-30 10:57
Hi,

It is true that communication through files adds some delay. But ince both sides check for file changes every few milliseconds and allow up to 50 command files per default settings (`num_command_files`), the delay is relatively small in my experience. 

If the file is not readable, it would just try again a few milliseconds later. 

We provide a performance test, which can be run from both MT4/5 only and python/java/C#. Here the MT4/python versions:

https://github.com/darwinex/dwxconnect/blob/main/mql/DWX_Performance_Test_MT4.mq4

https://github.com/darwinex/dwxconnect/blob/main/python/tests/dwx_performance_test.py

it prints the average execution time for opening, modifying and closing orders. It only opens pending orders and not positions because the additional delay from filling an order is independent of MT4/python and therefore would just add a random factor to the results. 

When I run the MT4 version on a demo account, I get this result:
![MT4](https://user-images.githubusercontent.com/62796452/160813735-0e69fc0a-9f7e-47ca-b7a4-7ed424c55398.jpg)

Running it from python results in just a few ms additional delay:
![python](https://user-images.githubusercontent.com/62796452/160813743-ae286f6d-19b9-4646-912d-5fc688d14a2b.jpg)

To run this yourself, I advice to use a demo account and change `mt4_files_path ` and `entry_price` (the entry price must be below current EURUSD quote) in the python script. In the DWX_Server_MT4 EA you also have to allow more orders `MaximumOrders=100`. 

The main goal with this project was to provide an solution that is easy to understand for beginners and that could easily be extended, or migrated to different programming languages. If the few milliseconds delay are too much for your strategy, then MT4 itself might also not be the best options. You could also try to improve execution by sending pending orders before the price reaches the entry threshold.

**Comment by xoomp** [comment] 2022-04-15 15:07
Why not use the socket interface officially provided by mql? And both mql4 and mql5 can be used normally, and there is an event solution for message reception. 

https://www.mql5.com/en/blogs/post/706665

Is this approach worth trying? Or have other issues been discovered?

Thanks.

**Comment by Boscop** [comment] 2022-04-18 15:18
I'm also concerned about performance, especially during backtesting.
I can imagine backtesting would be really slow with this file based communication mechanism, has anyone measured it?

@xoomp That socket post/lib is from 2017, does it still work nowadays? If so, I think that's the proper way to go..

**Comment by elvinex** [comment] 2022-04-19 08:58
Hi,

@xoomp Our goal was to provide a simple solution with as little dependencies as possible. 
Relying on third party libraries like the one provided in the blog post (it seems not to be included in the official code base) can be an issue for example after MetaTrader updates. This was the case at least once for our ZeroMQ solution, where an MT4 update lead to errors in an mql library that had to be updated as well. 
The current solution is also much easier to code for any programming language supporting file operations and is therefore also a good starting point for beginners who want to learn algorithmic trading. 

We also still support the ZeroMQ project, which can be used if you prefer socket based communication. We preferred to use ZeroMQ over Winsock because of its cross-platform capabilites. With Winsock you are limited to Windows from the start. 

@Boscop Neither of the projects can be used for backtesting. I am not 100% sure, but I don't think it is possible to control the MetaTrader backtest from any EA/script. Or if it is possible then I don't think there would be any callback to an outside trade logic, so you might as well just use MetaTrader alone. There are also great python-only backtesting tools.

**Comment by Boscop** [comment] 2022-04-21 15:02
@elvinex Thanks for your response :)

> The current solution is also much easier to code for any programming language supporting file operations and is therefore also a good starting point for beginners who want to learn algorithmic trading.

> Neither of the projects can be used for backtesting. 

If no backtesting is possible, this project seems not suitable for beginners like me, but only for people who already have profitable strategies implemented in other languages :/
Backtesting is probably more important for beginners than live trading. (Shouldn't we backtest our strategies before trading them live?)

> I am not 100% sure, but I don't think it is possible to control the MetaTrader backtest from any EA/script. 

I don't mean to control the backtesting from an EA, but to control the backtesting manually via MT's UI, so that it calls the EA for every tick (just like with EAs implemented in MQL), and just like during live trading. 
This should be possible with this lib, right?  (Although very slow with the current file-based communication.)

Could it even lead to wrong backtesting results, if the time in MT's backtesting engine runs faster than the processing of the communication?
Or is each tick's handler being processed until it finishes, before MT's engine will advance to the next tick? (In lockstep)
In other words, when the MT EA calls out to the user script (via the files or ZMQ), does it do it synchronously and wait for a response for this tick before letting MT advance to the next tick? Or will it run through the ticks as fast as possible, only sending out tick info but not waiting for a response, and whenever a command comes in, it might be arriving too late because it was meant to be a reaction to a tick that was far in the simulated past?

> There are also great python-only backtesting tools.

Which ones do you mean? The ones I found all have certain problems..

Btw, I would like to implement my strategy in Rust and use MTs backtesting engine to test my strategy. 
So it would be great if this project could work for backtesting in MT (4 & 5) 🙂

> Relying on third party libraries like the one provided in the blog post (it seems not to be included in the official code base) can be an issue for example after MetaTrader updates.

You could just implement a socket-based communication inspired by that lib, but adapt it to this project's needs, so that it wouldn't be an external dependency, how about that? :)

**Comment by elvinex** [comment] 2022-04-21 16:27
@Boscop You are right, in theory backtesting could work since file reading/writing should be possible. 

But the code would probably have to be adjusted to avoid the issues you mentioned if that is even possible. And even then, it would be much slower than a normal backtest. 
At the moment we are not considering investing time into such a solution, which would be inefficient at best. But we are happy to review pull requests in that direction. 

Socket based communication does not seem to be supported by the Strategy Tester, so it is also not an option:
https://www.mql5.com/en/forum/313177

Here, workarounds are mentioned but as I understand, the first one is file based and the second one would not use the Strategy Tester at all:
https://www.fxdesignlab.com/wp-content/uploads/2020/08/EA-Comm-by-Sockets-with-the-MT4-Tester.pdf

Generally, if your trade logic uses mostly technical indicators etc., an MT-only solution would be best. And if you use things like machine learning, then the backtesting process would be very different to MT anyway. 
There are also many other use cases, which do not necessarily need backtesting, like parsing website data to generate trade signals, coding an own trading app, etc. 

I only have some experience with python libraries "bt" and "backtesting" using daily data, but not sure if it would work well with tick data.

**Comment by elvinex** [comment] 2022-04-21 16:33
Actually, I haven't read the whole PDF before answering. 
It explains how to use sockets in the Tester, but it is also a bit messy workaround and I don't think we can provide a general solution for the problem with this project.

**Comment by Boscop** [comment] 2022-05-02 16:45
@elvinex Hm, what about DLL calls? Can MetaTrader EAs call into DLLs while backtesting, without issues?
Then I would compile my Rust code as a DLL and call it from MetaTrader.

**Comment by elvinex** [comment] 2022-05-03 05:59
I think it worked when I tested it, but it was a few years ago and maybe I don't remember correctly.

**Comment by Boscop** [comment] 2022-05-04 10:36
Thanks.
Btw, what was the reason for switching to this file-based communication mechanism? Just to make it work with MT5?
ZMQ also works with MT5: https://github.com/dingmaotu/mql-zmq

**Comment by elvinex** [comment] 2022-05-06 07:42
The ZeroMQ version is still a working alternative, so we didn't really switch. 
But the feedback we got was that the socket based approach and additional dependencies lead to users often having problems at the beginning, or not even being able to do some test trades. Therefore, we wanted to offer a simpler solution.

**Comment by elvinex** [comment] 2022-05-25 10:48
For completeness sake, I wrote a [performance test script](https://github.com/darwinex/dwx-zeromq-connector/blob/master/v2.0.1/python/examples/template/strategies/performance_test.py) for the ZeroMQ solution similar to the one for DWX Connect. It opens, modifies and closes 100 pending orders. The duration is similar, or even a bit higher. I think the variations are mainly caused by MT4 itself.

![image](https://user-images.githubusercontent.com/62796452/170245372-605356dc-da4c-46dc-a8e5-98466554ec77.png)

**Closed by elvinex** 2022-05-25 10:48 UTC
